language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - build-essential
            - cmake
      env:
        - MATRIX_EVAL="NPROC=$(nproc)"
    - os: osx
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL="NPROC=$(sysctl -n hw.physicalcpu)"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$(pwd)/install" ..
  - cmake --build . -- -j $NPROC

branches:
  only:
    # Pushes and PRs to the master branch.
    - master
    # Version tags.
    - /^v?\d+\.\d+.*$/

notifications:
  email:
    on_success: never
